---
jobs:
- name: job
  public: true

  plan:
  - task: new-pipelione
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo
        args: ["This is the new pipeline"]