---
jobs:
- name: job
  public: true
  plan:
  - task: Deploy
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo
        args: ["The Application is Deployed"]